version: '3.9'
services:
  teeception-agent:
    restart: always
    build:
      context: .
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/storage
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      X_USERNAME: ${X_USERNAME}
      X_PASSWORD: ${X_PASSWORD}
      X_CONSUMER_KEY: ${X_CONSUMER_KEY}
      X_CONSUMER_SECRET: ${X_CONSUMER_SECRET}
      X_CLIENT_MODE: "api"
      AGENT_TWITTER_CLIENT_PORT: "4000"
      PROTONMAIL_EMAIL: ${PROTONMAIL_EMAIL}
      PROTONMAIL_PASSWORD: ${PROTONMAIL_PASSWORD}
      STARKNET_RPC_URLS: ${STARKNET_RPC_URLS}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      CONTRACT_DEPLOYMENT_BLOCK: ${CONTRACT_DEPLOYMENT_BLOCK}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      X_LOGIN_SERVER_IP: ${X_LOGIN_SERVER_IP}
      X_LOGIN_SERVER_PORT: ${X_LOGIN_SERVER_PORT}
      SECURE_FILE: "/app/storage/secure.json"
      DSTACK_TAPPD_ENDPOINT: ""
      UNENCUMBER_ENCRYPTION_KEY: ${UNENCUMBER_ENCRYPTION_KEY}
      DEBUG_SHOW_SETUP: ${DEBUG_SHOW_SETUP}
      DEBUG_SHOW_PASSWORD: ${DEBUG_SHOW_PASSWORD}
      DEBUG_DISABLE_REPLIES: ${DEBUG_DISABLE_REPLIES}
      DEBUG_DISABLE_ENCUMBERING: ${DEBUG_DISABLE_ENCUMBERING}
