version: '3.9'
services:
  teeception-agent:
    build:
      context: .
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /tmp/tapp-ramdisk:/tmp/tapp-ramdisk
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      X_USERNAME: "your_twitter_username"
      X_PASSWORD: "your_twitter_password"
      X_CONSUMER_KEY: "your_twitter_app_key"
      X_CONSUMER_SECRET: "your_twitter_app_secret"
      AGENT_TWITTER_CLIENT_PORT: "3000"
      PROTONMAIL_EMAIL: "your_proton_email"
      PROTONMAIL_PASSWORD: "your_proton_password"
      STARKNET_RPC_URL: "your_ethereum_rpc_url"
      CONTRACT_ADDRESS: "your_contract_address"
      OPENAI_API_KEY: "your_openai_api_key"
      X_LOGIN_SERVER_IP: "your_twitter_login_server_ip"
      X_LOGIN_SERVER_PORT: "your_twitter_login_server_port"
      SECURE_FILE: "/tmp/tapp-ramdisk/secure.json"
      DEBUG_SHOW_SETUP: "true"
      DEBUG_SHOW_PASSWORD: "true"
      DEBUG_DISABLE_REPLIES: "true"

